name: Deploy Stuff 🧙‍♂️

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-[a-z]+"

permissions:
  packages: write
  pages: write
  id-token: write
  contents: read

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    env:
      GIT_LFS_SKIP_SMUDGE: 1
      REGISTRY_URL: ghcr.io
      
    strategy:
      fail-fast: true
      matrix:
        docker:
          [
            { image: chain, context: chain, cache_scope: "chain" },
            { image: webserver, context: webserver, cache_scope: "webserver" },
            { image: block-index-builder, context: block-index, cache_scope: "block-index" },
          ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - id: get_version
        uses: battila7/get-version-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: Login to GHCR
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push
        id: push
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: ${{ matrix.docker.context }}/Dockerfile
          push: true
          tags: ${{ env.REGISTRY_URL }}/anoma/namada-masp-indexer:${{ matrix.docker.image }}-${{ steps.get_version.outputs.version-without-v }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.docker.cache_scope }}
          cache-to: type=gha,scope=${{ matrix.docker.cache_scope }},mode=max

  swagger-ui:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@eff65dc3f193f0a749872be82f74baa35be0797d # v1
        with:
          output: swagger-ui
          spec-file: swagger.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Pages
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5
      - name: Upload artifact
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3
        with:
          path: 'swagger-ui'
      - name: Deploy to GitHub Pages
        if: startsWith(github.ref, 'refs/tags/v')
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4